# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    esi: true
    #fragments: true
    #serializer:
    #    name_converter: 'serializer.name_converter.camel_case_to_snake_case'

when@prod:
    framework:
        trusted_proxies: '127.0.0.1,localhost,172.18.0.0/8'
        trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

when@dev:
    framework:
        http_client:
            default_options:
                verify_peer: false
                
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
