# config/packages/html_sanitizer.yaml
framework:
    html_sanitizer:
        sanitizers:
            app.post_sanitizer:
                max_input_length: -1 #unlimited
                allow_safe_elements: true
                allow_static_elements: true

                allow_elements:
                    img: ['src', 'class', 'data-file-id', 'data-file-synced', 'data-lazy-load', 'style', 'alt', 'loading', 'decoding', 'fetchpriority', 'width', 'height']
                    figure: ['class']
                    
                # remove elements, but process the children
                block_elements: ['section']
                allow_relative_links: true
                allow_relative_medias: true