# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                location: '%app.public-upload-directory%'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
