# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        # This is a mapping example, remove it and create your own mappings.
        uploads:
            frontend: custom
            custom_frontend:
                class: App\Controller\FileManager\UploadController
                name: uploads

            namer: App\Common\UploadNamer
            storage:
                type: flysystem
                filesystem: oneup_flysystem.public_uploads_filesystem_filesystem
