controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#this rules should come after the default one.
controllers_admin:
    resource:
        path: ../src/Controller/Admin/
        namespace: App\Controller\Admin
    type: attribute
    prefix: /admin