# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name: '%env(APP_NAME)% Consulting Firm'
    router.request_context.scheme: '%env(APP_REQUEST_SCHEME)%'
    asset.request_context.secure: '%env(bool:APP_REQUEST_SECURE)%'
    app.base-upload-directory: 'uploads'
    app.base-upload-url: '%env(APP_BASE_URL)%/%app.base-upload-directory%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    app.public-upload-directory: '%kernel.project_dir%/public/%app.base-upload-directory%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicUploadsFilesystem: '@oneup_flysystem.public_uploads_filesystem_filesystem'
            $publicLocalStorage: '@oneup_uploader.storage.uploads'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
    Symfony\Component\Asset\Context\RequestStackContext: '@assets.context'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Common\UploadHelper:
        public: true
    App\Common\UploadNamer:
        public: true
    App\Common\LazifyImageContent:
        public: true
    App\Common\BreadcrumbBuilder:
        arguments:
            $homeRoute: 'app_admin_homepage'
    App\Controller\FileManager\UploadController:
        tags: ['controller.service_arguments']

    app.imagine.cache.format_extension:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\FormatExtensionResolver
        arguments:
            - "@liip_imagine.cache.resolver.flysystem_resolver"
            - "@liip_imagine.filter.configuration"
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "format_extension" }